### ISSUE TITLE
Our First Thing

### ISSUE THREAD

**Issue by nmsanchez** [vayaconsulting/learning-to-git#1]
Well hello, Amanda + Bianca. Welcome! Let's see what we can do with this little area.  Please respond to this issue with some thoughts.  

You can also add emojis by starting with a colon (:) and seeing what pops up. Just type : and then some words to see if it is an emoji. For example, I am typing : thumbs up with no spaces to get :+1: You won't see the picture until you click "Submit new issue" below.

Go ahead and try it!

**Comment by agelender** [comment]
Is what we are doing right now public? :8ball:

**Comment by nmsanchez** [comment]
Yes. :sheep: But no one is looking.

**Comment by bescalante** [comment]
I'm here mamacitas :dancer:

**Comment by bescalante** [comment]
And Age Lender is rocking that red :lipstick:

**Comment by nmsanchez** [comment]
Age Lender with eyes and lips on fleeeeeek. :eyes: 

A+ for both @agelender + @bescalante on this exercise.
