### ISSUE TITLE
Bianca has an issue

### ISSUE THREAD

**Issue by bescalante** [vayaconsulting/learning-to-git#2]
I'm debating whether or not to add a pic to my account. Also, do I want to add a pic of me or something I love? I notice Hubbers are pretty creative in this area..

**Comment by nmsanchez** [comment]
Oh @bescalante, you have so many issues. I think you should use a photo of your face so people get to know you first. :dancer:

**Comment by nmsanchez** [comment]
Your next assignment is to CLOSE your respective issues, @bescalante + @agelender. Go ahead and give it a try.
