### ISSUE TITLE
Impostor Syndrome

### ISSUE THREAD

**Issue by agelender** [vayaconsulting/learning-to-git#3]
Good morning! I have been doing some reading on Impostor Syndrome and I came across a couple of things I wanted to share. 

http://newlatina.net/latina-cubicle-confidential-the-impostor-syndrome-among-latinas/

http://everydayfeminism.com/2014/08/combat-imposters-syndrome/

**Comment by nmsanchez** [comment]
Ooh, @bescelante, do you see these great pieces?

Nicely done.

**Comment by bescalante** [comment]
Aw, you're so rad Amanda. Reading now...
