### ISSUE TITLE
Mastering Markdown 

### ISSUE THREAD

**Issue by agelender** [vayaconsulting/learning-to-git#5]
I'm not feeling very creative right now (_low on spoons!_) So I am just going to free associate here and add in some of the markdown bits. 

**Here are some thing I want or need to incorporate into my life right now:**
- Creative outlet
- A place to live that is mine
- Alone time
- Movement
- Magic
- Meditation
- Regular journaling
- Processing past events
- Drinking water
- Outlets for rage
- Good boundaries

**Things I do not need:**
- ~~People who bring me down~~
- ~~Crappy food~~
- ~~Negative self-talk~~
- ~~Crippling self-doubt~~
- ~~Racist white people~~

But then there are always these [animal cams](http://www.apl.tv/chicks.htm), so I guess things will be okay.

@nmsanchez
@bescalante

**Comment by nmsanchez** [comment]
:star2: :star: :dizzy: for @agelender!

**Comment by bescalante** [comment]
These animal cams tho!!!
