### ISSUE TITLE
Mastering Markdown

### ISSUE THREAD

**Issue by bescalante** [vayaconsulting/learning-to-git#6]
Hey @agelender I saw your post and had an idea :bulb: 

I have a :dog: sitting gig from 5/21-5/25 and Deo will be staying with me at this fancy home in the Castro so I thought: Why not offer Amanda my place in SF so she can have a little quality alone time? If you want, you can invite Isicera to stay with you too. It'll be like a little weekend getaway! 

# Amanda's Memorial Day Getaway
## Reasons to Accept:
- You deserve a respite. Not having a permanent place to stay takes a serious toll on one's well-being.
- It can be a great way to build up spoons. Even if all you do is stay in and watch tv! We have:
  - HBO Go
  - Hulu Plus
  - Netflix
- I can leave you an example of my Renter's Resume which you can copy and then use to give to potential landlords when you go see new apartments. It's a great way to "wow" them. 
- There are really too many reasons to list!

## Things to do:
- Visit nearby neighborhoods
  - Hayes Valley
  - The Mission
  - SOMA
  - Union Square

## Places to eat. 
I know you're a vegan and I'm not sure how vegan friendly these places are but here goes:
  - [Chantal Guillon for French Macarons!] (http://www.chantalguillon.com/)
  - [Grandma's Deli & Cafe - great fruit smoothies and Mexican Mocha's] (http://www.yelp.com/biz/grandmas-deli-and-cafe-san-francisco)
  - [Moya Ethiopian Restaurant] (http://www.eatmoya.com/)
  - [Blue Bottle Coffee @ Vega] (http://www.yelp.com/biz/vega-at-langton-san-francisco-2)

*SAY __YES__ PLEASE!*

### I didn't want to ignore you so I've been thinking about which Octocat I like **best**. I definitely like this guy:

![Image of Octocat de Los Muertos] (https://octodex.github.com/images/octocat-de-los-muertos.jpg)

but I'm also partial to... Spocktocat!

![Image of Spocktocat] (https://octodex.github.com/images/spocktocat.png)

Nevertheless, there are :two: things I need to get to the bottom of:
1. Why he's not called pentacat. In every pic he only has :five: limbs
2. Why hasn't anyone created a **Doctor Who** octocat - Hello?

(Yes, this took my like 45 minutes to do!)

**Comment by nmsanchez** [comment]
:star2: :star: :dizzy: for @bescalante !  And @agelender, I hope you will consider taking her up on this. Not because I want you out, but because I know that you could use some quiet time.  

I have many things to say about the :octocat: but will reserve those for an in-person meeting.

**Comment by agelender** [comment]
Okay WOW! Yes, that would be wonderful, thank you Bianca! Also, can I just say I admire your markdown technique? How are y'all doing the emojis?

Also, I heard from Nicole that you have apartment rental skills for days - any and all tips are welcome! I am struggling with the fact that my credit is not that good and the competition is CRAZY!

Thank you again so much!

**Comment by bescalante** [comment]
Yay! I'll make sure write up info and we'll figure out a time for you to get my key later.

### Apartment Hunting
Ugh, I remember what that was like and I totally had to step outside my comfort zone in order to stand out. It's SO COMPETITIVE!

I'd get to places early (or stay late) and make sure that I had some one-on-one time with the person showing the place. If they were showing it on behalf of a landlord, I'd ask for the landlord's number so I could call them and introduce myself and tell them how much I love the place. In some instances, I'd call the landlord *while there were still other people looking at the apartment* and get lots of dirty looks. :open_mouth: 

It sucks, but I had to play dirty. :hankey: 

p.s. For emoji's just enter ` : ` followed by any of the words on the [Emoji Cheat Sheet] (http://www.emoji-cheat-sheet.com/)
